var sqlite3 = require('sqlite3').verbose();
var databaseFile='../keymap.db';
var db = new sqlite3.Database(databaseFile);
var defaultKeymap=[[0,0],[[[["KC_ESC"],["KC_F1"],["KC_F2"],["KC_F3"],["KC_F4"],["KC_F5"],["KC_F6"],["KC_F7"],["KC_F8"],["KC_F9"],["KC_F10"],["KC_F11"],["KC_F12"],["KC_PSCR"],["KC_SLCK"],["KC_INS"]],[["KC_GRV"],["KC_1"],["KC_2"],["KC_3"],["KC_4"],["KC_5"],["KC_6"],["KC_7"],["KC_8"],["KC_9"],["KC_0"],["KC_MINS"],["KC_EQL"],["KC_BSPC"],["KC_DEL"]],[["KC_TAB"],["KC_Q"],["KC_W"],["KC_E"],["KC_R"],["KC_T"],["KC_Y"],["KC_U"],["KC_I"],["KC_O"],["KC_P"],["KC_LBRC"],["KC_RBRC"],["KC_BSLS"],["KC_PGUP"]],[["KC_CAPS"],["KC_A"],["KC_S"],["KC_D"],["KC_F"],["KC_G"],["KC_H"],["KC_J"],["KC_K"],["KC_L"],["KC_SCLN"],["KC_QUOT"],["KC_ENT"],["KC_PGDN"]],[["KC_LSFT"],["KC_Z"],["KC_X"],["KC_C"],["KC_V"],["KC_B"],["KC_N"],["KC_M"],["KC_COMM"],["KC_DOT"],["KC_SLSH"],["KC_RSFT"],["KC_UP"],["KC_FN",[1,[1]]]],[["KC_LCTRL"],["KC_LGUI"],["KC_LALT"],["KC_SPC"],["KC_RALT"],["KC_RCTRL"],["KC_LEFT"],["KC_DOWN"],["KC_RGHT"]]],[[["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"]],[["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"]],[["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"]],[["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"]],[["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"]],[["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"]]]],"epbt75","1.2","hex"];
var wkl=[[0,0],[[[["KC_ESC"],["KC_F1"],["KC_F2"],["KC_F3"],["KC_F4"],["KC_F5"],["KC_F6"],["KC_F7"],["KC_F8"],["KC_F9"],["KC_F10"],["KC_F11"],["KC_F12"],["KC_PSCR"],["KC_SLCK"],["KC_INS"]],[["KC_GRV"],["KC_1"],["KC_2"],["KC_3"],["KC_4"],["KC_5"],["KC_6"],["KC_7"],["KC_8"],["KC_9"],["KC_0"],["KC_MINS"],["KC_EQL"],["KC_BSPC"],["KC_DEL"]],[["KC_TAB"],["KC_Q"],["KC_W"],["KC_E"],["KC_R"],["KC_T"],["KC_Y"],["KC_U"],["KC_I"],["KC_O"],["KC_P"],["KC_LBRC"],["KC_RBRC"],["KC_BSLS"],["KC_PGUP"]],[["KC_CAPS"],["KC_A"],["KC_S"],["KC_D"],["KC_F"],["KC_G"],["KC_H"],["KC_J"],["KC_K"],["KC_L"],["KC_SCLN"],["KC_QUOT"],["KC_ENT"],["KC_PGDN"]],[["KC_LSFT"],["KC_Z"],["KC_X"],["KC_C"],["KC_V"],["KC_B"],["KC_N"],["KC_M"],["KC_COMM"],["KC_DOT"],["KC_SLSH"],["KC_RSFT"],["KC_UP"],["KC_FN",[1,[1]]]],[["KC_LCTRL"],["KC_LGUI"],["KC_LALT"],["KC_SPC"],["KC_RALT"],["KC_RCTRL"],["KC_LEFT"],["KC_DOWN"],["KC_RGHT"]]],[[["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_PAUS"]],[["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"]],[["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"]],[["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_HOME"],["KC_END"],["KC_TRNS"],["KC_TRNS"]],[["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_VOLU"],["KC_VOLD"],["KC_MUTE"],["KC_TRNS"],["KC_LED_DE"],["KC_TRNS"]],[["KC_TRNS"],["KC_LOCK_WIN"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_TRNS"],["KC_LED_TOGGLE"],["KC_LED_IN"],["KC_LED_TOGGLE"]]]],"epbt75","1.2","bin"];
db.serialize(function() {
    db.run("delete from keymaps where key='epbt75'");
    db.run("delete from keymaps where key='epbt75_wkl'");
    db.run("delete from keymaps where key='epbt75_wk'");
    db.run("insert into keymaps values('epbt75','epbt75','"+JSON.stringify(wkl)+"')");
    db.run("insert into keymaps values('epbt75_wkl','epbt75_wkl','"+JSON.stringify(wkl)+"')");
    db.run("insert into keymaps values('epbt75_wk','epbt75_wk','"+JSON.stringify(wkl)+"')");
});

db.close();